# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/knuthy/projects/abcd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/knuthy/projects/abcd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/knuthy/projects/abcd/CMakeFiles /home/knuthy/projects/abcd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/knuthy/projects/abcd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named abcd

# Build rule for target.
abcd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 abcd
.PHONY : abcd

# fast build rule for target.
abcd/fast:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/build
.PHONY : abcd/fast

#=============================================================================
# Target rules for targets named test_abcd

# Build rule for target.
test_abcd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_abcd
.PHONY : test_abcd

# fast build rule for target.
test_abcd/fast:
	$(MAKE) -f test/CMakeFiles/test_abcd.dir/build.make test/CMakeFiles/test_abcd.dir/build
.PHONY : test_abcd/fast

src/abcd.o: src/abcd.cpp.o
.PHONY : src/abcd.o

# target to build an object file
src/abcd.cpp.o:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/abcd.cpp.o
.PHONY : src/abcd.cpp.o

src/abcd.i: src/abcd.cpp.i
.PHONY : src/abcd.i

# target to preprocess a source file
src/abcd.cpp.i:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/abcd.cpp.i
.PHONY : src/abcd.cpp.i

src/abcd.s: src/abcd.cpp.s
.PHONY : src/abcd.s

# target to generate assembly for a file
src/abcd.cpp.s:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/abcd.cpp.s
.PHONY : src/abcd.cpp.s

src/bcg.o: src/bcg.cpp.o
.PHONY : src/bcg.o

# target to build an object file
src/bcg.cpp.o:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/bcg.cpp.o
.PHONY : src/bcg.cpp.o

src/bcg.i: src/bcg.cpp.i
.PHONY : src/bcg.i

# target to preprocess a source file
src/bcg.cpp.i:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/bcg.cpp.i
.PHONY : src/bcg.cpp.i

src/bcg.s: src/bcg.cpp.s
.PHONY : src/bcg.s

# target to generate assembly for a file
src/bcg.cpp.s:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/bcg.cpp.s
.PHONY : src/bcg.cpp.s

src/cimmino.o: src/cimmino.cpp.o
.PHONY : src/cimmino.o

# target to build an object file
src/cimmino.cpp.o:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/cimmino.cpp.o
.PHONY : src/cimmino.cpp.o

src/cimmino.i: src/cimmino.cpp.i
.PHONY : src/cimmino.i

# target to preprocess a source file
src/cimmino.cpp.i:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/cimmino.cpp.i
.PHONY : src/cimmino.cpp.i

src/cimmino.s: src/cimmino.cpp.s
.PHONY : src/cimmino.s

# target to generate assembly for a file
src/cimmino.cpp.s:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/cimmino.cpp.s
.PHONY : src/cimmino.cpp.s

src/comms.o: src/comms.cpp.o
.PHONY : src/comms.o

# target to build an object file
src/comms.cpp.o:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/comms.cpp.o
.PHONY : src/comms.cpp.o

src/comms.i: src/comms.cpp.i
.PHONY : src/comms.i

# target to preprocess a source file
src/comms.cpp.i:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/comms.cpp.i
.PHONY : src/comms.cpp.i

src/comms.s: src/comms.cpp.s
.PHONY : src/comms.s

# target to generate assembly for a file
src/comms.cpp.s:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/comms.cpp.s
.PHONY : src/comms.cpp.s

src/mc77ad.o: src/mc77ad.f.o
.PHONY : src/mc77ad.o

# target to build an object file
src/mc77ad.f.o:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/mc77ad.f.o
.PHONY : src/mc77ad.f.o

src/mmio.o: src/mmio.cpp.o
.PHONY : src/mmio.o

# target to build an object file
src/mmio.cpp.o:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/mmio.cpp.o
.PHONY : src/mmio.cpp.o

src/mmio.i: src/mmio.cpp.i
.PHONY : src/mmio.i

# target to preprocess a source file
src/mmio.cpp.i:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/mmio.cpp.i
.PHONY : src/mmio.cpp.i

src/mmio.s: src/mmio.cpp.s
.PHONY : src/mmio.s

# target to generate assembly for a file
src/mmio.cpp.s:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/mmio.cpp.s
.PHONY : src/mmio.cpp.s

src/mumps.o: src/mumps.cpp.o
.PHONY : src/mumps.o

# target to build an object file
src/mumps.cpp.o:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/mumps.cpp.o
.PHONY : src/mumps.cpp.o

src/mumps.i: src/mumps.cpp.i
.PHONY : src/mumps.i

# target to preprocess a source file
src/mumps.cpp.i:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/mumps.cpp.i
.PHONY : src/mumps.cpp.i

src/mumps.s: src/mumps.cpp.s
.PHONY : src/mumps.s

# target to generate assembly for a file
src/mumps.cpp.s:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/mumps.cpp.s
.PHONY : src/mumps.cpp.s

src/preprocess.o: src/preprocess.cpp.o
.PHONY : src/preprocess.o

# target to build an object file
src/preprocess.cpp.o:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/preprocess.cpp.o
.PHONY : src/preprocess.cpp.o

src/preprocess.i: src/preprocess.cpp.i
.PHONY : src/preprocess.i

# target to preprocess a source file
src/preprocess.cpp.i:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/preprocess.cpp.i
.PHONY : src/preprocess.cpp.i

src/preprocess.s: src/preprocess.cpp.s
.PHONY : src/preprocess.s

# target to generate assembly for a file
src/preprocess.cpp.s:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/preprocess.cpp.s
.PHONY : src/preprocess.cpp.s

src/structure.o: src/structure.cpp.o
.PHONY : src/structure.o

# target to build an object file
src/structure.cpp.o:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/structure.cpp.o
.PHONY : src/structure.cpp.o

src/structure.i: src/structure.cpp.i
.PHONY : src/structure.i

# target to preprocess a source file
src/structure.cpp.i:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/structure.cpp.i
.PHONY : src/structure.cpp.i

src/structure.s: src/structure.cpp.s
.PHONY : src/structure.s

# target to generate assembly for a file
src/structure.cpp.s:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/structure.cpp.s
.PHONY : src/structure.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/abcd.dir/build.make CMakeFiles/abcd.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... abcd"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_abcd"
	@echo "... src/abcd.o"
	@echo "... src/abcd.i"
	@echo "... src/abcd.s"
	@echo "... src/bcg.o"
	@echo "... src/bcg.i"
	@echo "... src/bcg.s"
	@echo "... src/cimmino.o"
	@echo "... src/cimmino.i"
	@echo "... src/cimmino.s"
	@echo "... src/comms.o"
	@echo "... src/comms.i"
	@echo "... src/comms.s"
	@echo "... src/mc77ad.o"
	@echo "... src/mmio.o"
	@echo "... src/mmio.i"
	@echo "... src/mmio.s"
	@echo "... src/mumps.o"
	@echo "... src/mumps.i"
	@echo "... src/mumps.s"
	@echo "... src/preprocess.o"
	@echo "... src/preprocess.i"
	@echo "... src/preprocess.s"
	@echo "... src/structure.o"
	@echo "... src/structure.i"
	@echo "... src/structure.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

